### ISSUE TITLE
Monocart report will not include all files

### ISSUE THREAD

**Issue by stevez** [cenfun/jest-monocart-coverage#1]
I found a strange issue, if I commented out the jest coverage reports, like this

//coverageReporters: ['none']

Then the console will output 2 coverage results, I believe the first one is from monocart jest repot, the 2nd one is from jest, and the first one does not include all files

If I set disable the coverageReporters field, then I will see only 1 coverage result, which does not include all files

**Comment by cenfun** [comment]
yes [coverageReporters](https://jestjs.io/docs/configuration#coveragereporters-arraystring--string-options) is a Jest option, it will generate istanbul coverage reports by jest. and Monocart also can generate istanbull coverage reports, we don't need two, just pick one.

**Comment by stevez** [comment]
It works in 1.1.0
