### ISSUE TITLE
'all' property config is not working

### ISSUE THREAD

**Issue by stevez** [cenfun/jest-monocart-coverage#2]
When I tried to add 'all' property to include all the files, I found it is not working in the jest report

**Comment by cenfun** [comment]
I believe the 'all' option works, unless you are not using the latest version.
For example, the npm cache with `package-lock.json`, anyway I just release a new version jest-monocart-coverage@1.0.4 which will install latest version `mcr`, please try it, or remove `package-lock.json` and reisnstall.

```
module.exports = {

    // Enable coverage
    collectCoverage: true,
    // Recommended to use `v8` to support the generation of native v8 coverage reports.
    coverageProvider: 'v8',
    // Monocart can also support all coverage reports, so there is no need to set up reports here.
    coverageReporters: ['none'],

    reporters: [
        // If custom reporters are specified, the default Jest reporter will be overridden. If you wish to keep it, 'default' must be passed as a reporters name:
        'default',

        // Monocart custom reporter to generate coverage reports.
        ['jest-monocart-coverage', {
            // logging: 'debug',
            name: 'Jest Monocart Coverage Report',

            outputDir: './coverage-reports/v8',

            all: './src',

            sourcePath: {
                'src/': ''
            },

            reports: [
                'v8',
                'codecov',
                'raw',
                'text'
            ]
        }]
    ]

};

```
sets `all` for monocart not jest, see [example](https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#adding-empty-coverage-for-untested-files)

**Comment by stevez** [comment]
![image](https://github.com/cenfun/jest-monocart-coverage/assets/152627/a43bf726-98bc-47ec-abd8-5f007f232272)

I tried the 1.0.4 and it is not working. Attached the screenshot shows the first one is generated by monocart, the second one is generated by jest

**Comment by cenfun** [comment]
could you share your jest configuration?

**Comment by stevez** [comment]
coverageReporters: [
      ['lcov'],
      ['json'],
      ['text-summary']
    ],
    reporters: [
      'default',
      ['jest-monocart-coverage', {
          logging: 'debug',
          name: 'Unit Tests Coverage Report',
          reports: [
            ['raw'],
            ['lcov'],
            ['json'],
            ['text-summary']
          ],
          all: {
            dir: ['./src'],
            filter: {
              // exclude files
              '**/*.test.js': false,
              '**/__tests__/**': false,
              '**/*.js': true
            }
          },
          onEnd: () => {
            console.log('onEnd is called.');
          }
         
      }]
    ],

**Comment by cenfun** [comment]
Is it possible that there's an issue with the filter? 
Could you try removing this filter and try again?
```js
filter: {
// exclude files
'/*.test.js': false,
'/tests/': false,
'/*.js': true
}
```
Or maybe try writing it this way.
```js
filter: {
// exclude files
'**/*.test.js': false,
'**/tests/*': false,
'**/*.js': true
}
```

**Comment by stevez** [comment]
Those are copied from playwright config, let me try. Or could you share your example repo let me try to reproduce it?

**Comment by cenfun** [comment]
Try current repo https://github.com/cenfun/jest-monocart-coverage
```
npm i
npm run test
```
![image](https://github.com/cenfun/jest-monocart-coverage/assets/334577/d04d3187-e6ad-4c23-82a5-821379ff4537)

**Comment by stevez** [comment]
Please use this jest.config.js

`
module.exports = {
 
    // Enable coverage
    collectCoverage: true,
    coverageDirectory: "./coverage-reports/istanbul",
    collectCoverageFrom: [
      "src/**/*.js"
    ],
    // Recommended to use `v8` to support the generation of native v8 coverage reports.
    //coverageProvider: 'v8',
    // Monocart can also support all coverage reports, so there is no need to set up reports here.
    //coverageReporters: ['none'],
    coverageReporters: [
        ['lcov'],
        ['json'],
        ['text'],
        ['text-summary']
    ],
 
    reporters: [
        // If custom reporters are specified, the default Jest reporter will be overridden. If you wish to keep it, 'default' must be passed as a reporters name:
        'default',
 
        // Monocart custom reporter to generate coverage reports.
        ['./lib', {
            // logging: 'debug',
            name: 'Jest Monocart Coverage Report',
 
            //outputDir: './coverage-reports/istanbul',
 
            all: './src',
 
            sourcePath: {
                'src/': ''
            },
 
            reports: [
                ['raw'],
                ['lcov'],
                ['json'],
                ['text'],
                ['text-summary']
            ],
 
            onEnd: () => {
                console.log('onEnd');
            }
        }]
    ],
 
    globalTeardown: './global-teardown.js'
 
};
`

npm run test

npx jest test/wrapped.test.js

![image](https://github.com/cenfun/jest-monocart-coverage/assets/152627/de5dc5b2-6fa1-4a34-926f-a4a17b2d1d66)

**Comment by cenfun** [comment]
I know your concern now. For Istanbul reports like `text` and `text-summary`, there are different calculation results between monocart and jest(v8-to-istanbul).
It should be able to be fixed for the `all` option

**Comment by cenfun** [comment]
Moreover, I want to clarify that the Monocart is designed to handle V8's coverage data directly, or convert V8 to Istanbul. However, if you're directly using Istanbul's data, it's recommended to use Istanbul's reports directly, no need using Monocart.

**Comment by stevez** [comment]
Is it going to be fixed for Istanbul? We do have a plan of using v8, but right now we have to stick with Istanbul.

The reason I choose jest monocart report is I need raw coverage files in order to merge with playwright test using the monocart reporter, if you have a solution of generating raw files in jest, please let me know. Thanks

**Comment by cenfun** [comment]
@stevez  It should be fixed in version jest-monocart-coverage@1.1.0
![image](https://github.com/cenfun/jest-monocart-coverage/assets/334577/7ee3596e-8904-4740-b870-b8a39b3f56b8)

**Comment by stevez** [comment]
If this works then we can disable the jest report and use only the monocart report

**Comment by stevez** [comment]
Yes it works now
