### ISSUE TITLE
onEnd() is called before the jest global teardown

### ISSUE THREAD

**Issue by stevez** [cenfun/jest-monocart-coverage#3]
Based on the console output shows the order

**Comment by cenfun** [comment]
So, for Jest, you want to add more coverage data to the coverage report in the global teardown?

**Comment by cenfun** [comment]
For jest, the `onEnd` is called after the `onRunComplete`, https://github.com/jestjs/jest/blob/main/packages/jest-reporters/src/types.ts#L51

**Comment by stevez** [comment]
> So, for Jest, you want to add more coverage data to the coverage report in the global teardown?

I want to copy the jest coverage to another folder after the test, so when we skip the playwright tests, we can still get the coverage

**Comment by cenfun** [comment]
For Playwright, the reporter onEnd is called after the global teardown, but for Jest, it is called before the global teardown. I do not think we can change this order.

**Comment by stevez** [comment]
Then please document this difference first

**Comment by cenfun** [comment]
Sure, Thanks for the suggestion.
